---
- name: Install php packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-cli
    - php5-fpm
    - php5-mysql
    - php5-mcrypt

- name: Enable php mcrypt
  shell: "php5enmod mcrypt"
  notify: Restart php-fpm
