---
- name: Configure Laravel
  shell: "php /vagrant/ansible/scripts/fill_syntara_config.php"

- name: Install Syntara (demo)
  shell: "php /vagrant/ansible/scripts/fill_syntara_composer.php {{ syntara_version }}.*"
  when: type == "demo"

- name: Check workbench directory existence
  stat: path=/vagrant/workbench
  register: workbench_existing
  when: type == "dev"

- name: Create workbench
  shell: "mkdir /vagrant/workbench && mkdir /vagrant/workbench/mrjuliuss"
  when: type == "dev" and not workbench_existing.stat.exists

- name: Creatre workbench directory
  shell: "cd /vagrant/workbench/mrjuliuss/"
  when: type == "dev"

- name: Get local dir
  sudo: false
  local_action: shell pwd
  register: local_dir

- name: Check syntara directory existence
  stat: path=/vagrant/workbench/mrjuliuss/syntara
  register: syntara_existing
  when: type == "dev"

- name: Git clone syntara
  connection: local
  sudo: false
  shell: "git clone -b {{ syntara_version }} git@github.com:MrJuliuss/syntara.git {{local_dir.stdout}}/../workbench/mrjuliuss/syntara"
  when: type == "dev" and not syntara_existing.stat.exists

- name: Composer update
  shell: "cd /vagrant && composer update"
  notify: Restart nginx
  when: type == "demo"

- name: Create syntara database
  mysql_db: name=syntara state=present

- name: Publish assets (demo)
  shell: "cd /vagrant && php artisan asset:publish mrjuliuss/syntara"
  when: type == "demo"

- name: Migrations (demo)
  shell: "cd /vagrant && php artisan migrate --package=cartalyst/sentry --force && php artisan migrate --package=mrjuliuss/syntara --force"
  when: type == "demo"

- name: Publish assets (dev)
  shell: "cd /vagrant && php artisan asset:publish --path=workbench/mrjuliuss/syntara/public/ mrjuliuss/syntara"
  when: type == "dev"

- name: Migrations (dev)
  shell: "cd /vagrant && php artisan migrate --path=workbench/mrjuliuss/syntara/src/migrations/ --package=mrjuliuss/syntara && php artisan migrate --path=workbench/mrjuliuss/syntara/vendor/cartalyst/sentry/src/migrations --package=cartalyst/sentry"
  when: type == "dev"

- name: Create admin Group
  shell: 'cd /vagrant && ./ansible/scripts/db.sh'

- name: Create user
  shell: "cd /vagrant && php artisan create:user admin admin@syntara.dev foobar Admin"
