---
- name: Check composer.json existence
  stat: path=/vagrant/composer.json
  register: laravel_installed

- name: Install Laravel
  command: "composer create-project laravel/laravel --prefer-dist /home/vagrant/laravel"
  when: not laravel_installed.stat.exists

- name: Move laravel files
  shell: "cp -R /home/vagrant/laravel/* /vagrant"
  when: not laravel_installed.stat.exists

- name: Remove tmp laravel folder
  shell: "rm -rf /home/vagrant/laravel"

- name: Chmod 777 on app/storage
  shell: "chmod 777 /vagrant/app/storage/logs"
  # Vagrant v1.1+

