---
- name: Install MySQL server
  sudo: yes
  apt:  pkg=mysql-server state=latest

- name: Install python-mysqldb
  apt: pkg=python-mysqldb state=latest

- name: Allow access to MySQL from anywhere
  sudo: yes
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" "line=#bind-address = 0.0.0.0"
  notify: Restart mysql
